main:
  - name: "Posts"
    url: /posts/
    weight: 1
  - name: "Jobs"
    url: /jobs/
    weight: 2

footer:
  - name: "Posts"
    url: /posts/
    weight: 1
  - name: "Jobs"
    url: /jobs/
    weight: 2

bottom:
  - name: "Privacy Policy"
    url: /privacy-policy
    weight: 1
  - name: "Terms of Service"
    url: /terms-of-service
    weight: 2
  - name: "RSS"
    url: /index.html
    weight: 3
